apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" $.Release.Name | trunc 63 | trimSuffix "-" }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ printf "%s-meetup" $.Release.Name | trunc 63 | trimSuffix "-" }}
  ports:
    - name: http
      port: 80
      targetPort: http
